// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// This is a placeholder file. In a real project, this is generated by
/// `flutterfire configure`. This example structure supports different
/// environments based on a compile-time variable, aligning with REQ-1-020.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    const String flavor = String.fromEnvironment('FLAVOR');

    switch (flavor) {
      case 'production':
        return production;
      case 'staging':
        return staging;
      case 'development':
      default:
        return development;
    }
  }

  // --- PLACEHOLDER: DEVELOPMENT ENVIRONMENT ---
  static const FirebaseOptions development = FirebaseOptions(
    apiKey: 'DEV_API_KEY_PLACEHOLDER',
    appId: '1:DEV_APP_ID:platform:DEV_APP_ID_SUFFIX',
    messagingSenderId: 'DEV_MESSAGING_SENDER_ID',
    projectId: 'myapp-dev',
    authDomain: 'myapp-dev.firebaseapp.com',
    storageBucket: 'myapp-dev.appspot.com',
    // Add other platform-specific keys
  );

  // --- PLACEHOLDER: STAGING ENVIRONMENT ---
  static const FirebaseOptions staging = FirebaseOptions(
    apiKey: 'STAGING_API_KEY_PLACEHOLDER',
    appId: '1:STG_APP_ID:platform:STG_APP_ID_SUFFIX',
    messagingSenderId: 'STG_MESSAGING_SENDER_ID',
    projectId: 'myapp-staging',
    authDomain: 'myapp-staging.firebaseapp.com',
    storageBucket: 'myapp-staging.appspot.com',
    // Add other platform-specific keys
  );

  // --- PLACEHOLDER: PRODUCTION ENVIRONMENT ---
  static const FirebaseOptions production = FirebaseOptions(
    apiKey: 'PROD_API_KEY_PLACEHOLDER',
    appId: '1:PROD_APP_ID:platform:PROD_APP_ID_SUFFIX',
    messagingSenderId: 'PROD_MESSAGING_SENDER_ID',
    projectId: 'myapp-prod',
    authDomain: 'myapp-prod.firebaseapp.com',
    storageBucket: 'myapp-prod.appspot.com',
    // Add other platform-specific keys
  );
}