# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This file is organized into four sections:
#
#   - analyzer:  Settings for the static analyzer.
#   - linter:    Rules and settings for the linter.
#   - flutter:   Settings for the Flutter specific aspects of the analyzer.
#
# For more information, see:
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  errors:
    # Treat these issues as warnings.
    dead_code: warning
    # Treat these issues as info.
    deprecated_member_use: info
    # Ignore these issues.
    # avoid_print: ignore

linter:
  # For a full list of available rules, see
  # https://dart-lang.github.io/linter/lints/options/options.html
  rules:
    # ------ Error Rules ------ #
    # These rules are critical for code correctness.
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - valid_regexps
    
    # ------ Style Rules ------ #
    # These rules enforce a consistent coding style.
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports # Critical for Clean Architecture
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - leading_newlines_in_multiline_strings
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - slash_for_doc_comments
    - sort_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_key_in_widget_constructors