name: app_mobile
description: A cross-platform mobile application for attendance tracking.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  firebase_core: ^2.27.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^13.2.1

  # Firebase Services
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  firebase_crashlytics: ^3.4.18
  firebase_performance: ^0.9.3+17

  # Device & Native APIs
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

  # Data Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI & UX
  cupertino_icons: ^1.0.6
  
  # Path dependencies to internal libraries
  # Assuming these are located in a parallel 'libs' directory
  # Adjust the path as per your monorepo structure
  attendance_client_data:
    path: ../libs/client/data_access
  attendance_client_ui:
    path: ../libs/client/ui
  attendance_shared_domain:
    path: ../libs/shared/domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  
  # Linting
  flutter_lints: ^3.0.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23